agent {
    data_dir = "/var/lib/spire-agent"
    log_level = "INFO"
    server_address = "127.0.0.1"
    server_port = "8085"
    socket_path = "/run/spire/agent.sock"
    trust_bundle_path = "/etc/spire/bootstrap.crt"
    trust_domain = "polyedge.local"
}

plugins {
    NodeAttestor "join_token" {
        plugin_data {}
    }

    KeyManager "disk" {
        plugin_data {
            directory = "/var/lib/spire-agent"
        }
    }

    WorkloadAttestor "unix" {
        plugin_data {
            discover_workload_path = true
            workload_size_limit = -1
        }
    }
}
