log_level = "info"
domains = ["oidc.aldoapicella.com"]
listen_socket_path = "/run/spire-oidc/provider.sock"
jwt_issuer = "https://oidc.aldoapicella.com"
jwks_uri = "https://oidc.aldoapicella.com/keys"
set_key_use = true

workload_api {
    socket_path = "/run/spire/agent.sock"
    trust_domain = "polyedge.local"
}

health_checks {
    bind_port = "8008"
}
